# Generated by Django 5.0.4 on 2024-04-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episodios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, unique=True)),
                ('thumb', models.ImageField(upload_to='thumbs_filmes')),
                ('descricao', models.TextField(blank=True, max_length=1000, null=True)),
                ('categoria', models.CharField(blank=True, choices=[('ANALISES', 'Analises'), ('PROGRAMACAO', 'Programacao'), ('APRESENTACAO', 'Apresentacao'), ('OUTROS', 'Outros')], max_length=32, null=True)),
                ('visualizacoes', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('episodios', models.ManyToManyField(blank=True, related_name='episodios_filme', to='filme_app.episodios')),
            ],
        ),
    ]
